<?php

/*
 * Copyright (c) 2020 Heimrich & Hannot GmbH
 *
 * @license LGPL-3.0-or-later
 */

namespace HeimrichHannot\TreeBundle\TreeNode;

use Contao\MemberGroupModel;
use Contao\Model\Collection;
use Contao\StringUtil;
use HeimrichHannot\TreeBundle\Event\ModifiyNodeLabelCallback;
use HeimrichHannot\UtilsBundle\Model\ModelUtil;

class MemberGroupNode extends AbstractTreeNode
{
    protected $iconHidden = 'mgroup_.svg';
    protected $iconPublished = 'mgroup.svg';
    /**
     * @var ModelUtil
     */
    private $modelUtil;

    /**
     * MemberGroupNode constructor.
     */
    public function __construct(ModelUtil $modelUtil)
    {
        $this->modelUtil = $modelUtil;
    }

    public static function getType(): string
    {
        return 'member_group';
    }

    public function onLabelCallback(ModifiyNodeLabelCallback $event): string
    {
        if (!isset($event->getRow()['groups'])) {
            return parent::onLabelCallback($event);
        }
        $groupIds = StringUtil::deserialize($event->getRow()['groups']);

        /** @var Collection|MemberGroupModel[]|MemberGroupModel $groups */
        if (empty($groupIds) || !($groups = $this->modelUtil->findMultipleModelInstancesByIds('tl_member_group', $groupIds))) {
            return parent::onLabelCallback($event); // TODO: Change the autogenerated stub
        }
        $label = $event->getLabel();

        if ($event->getHasChilds()) {
            $margin = '40';
        } else {
            $margin = '20';
        }
        $label .= '<br /><span style="font-style: italic;display: inline-block;margin-left: '.$margin.'px;margin-top: 5px;">'.implode(',', $groups->fetchEach('name')).'</span>';

        return $label;
    }

    protected function getPalette(): string
    {
        return '{content_legend},groups,description;';
    }
}
