services:
  _defaults:
    autowire: true

  HeimrichHannot\TreeBundle\EventListener\:
    resource: '../../EventListener/*'
    public: true

  HeimrichHannot\TreeBundle\TreeNode\:
    resource: '../../TreeNode/*'
    tags: ['huh.tree.node_type']

  HeimrichHannot\TreeBundle\OutputType\:
    resource: '../../OutputType/*'
    tags: ['huh.tree.output_type']

  HeimrichHannot\TreeBundle\Collection\NodeTypeCollection:
    arguments: [!tagged huh.tree.node_type]

  HeimrichHannot\TreeBundle\Collection\OutputTypeCollection:
    arguments: [!tagged huh.tree.output_type]

  HeimrichHannot\TreeBundle\Generator\TreeGenerator: ~